name: Create release tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version you want to release
        required: true
jobs:
  create-release-tag:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: create and push tag
      run: |
        git config --global user.name 'Release'
        git config --global user.email 'ingarabr@users.noreply.github.com'
        git tag -a v${{ github.event.inputs.version }} -m "${{ github.event.inputs.version }}"
        git push origin v${{ github.event.inputs.version }}
